#import pytest
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestFlightSearchFunctionality(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.get("https://www.united.com/en-us/flights-from-chicago-to-san-francisco")  # Replace with the actual URL

    def tearDown(self):
        self.driver.quit()

    def test_valid_one_way_flight_search(self):
        WebDriverWait(self.driver, 5).until(EC.presence_of_element_located((By.ID, "flights-booking-id-1-input")))
        departure_city_input = self.driver.find_element(By.XPATH, '//*[@id="main"]/div[1]/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div[2]/div[1]/div[1]/div/div/div/div/div')
        self.assertIn("Chicago", departure_city_input.text)
        #destination_city_input = self.driver.find_element(By.XPATH, "//*[@id="main"]/div[1]/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div[2]/div[1]/div[2]/div/div/div/div/div")
        #self.assertIn(destination_city_input.text, "San Francisco")
        #one_way_combo = Select(self.driver.find_element(By.ID, "headlessui-listbox-button-1"))
        #one_way_combo.select_by_visible_text("One-way")
        #search_btn = self.driver.find_element(By.XPATH, '//*[@id="main"]/div[1]/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div[2]/div[3]/button')
        #search_btn.click()
        #self.assertIn(destination_city_input.text, "San Francisco")
        #WebDriverWait(self.driver, 5).until(EC.presence_of_element_located((By.ID, "flights-booking-id-1-input")))
        #info_banner = self.driver.find_element(By.XPATH, '//*[@id="alert-content-atm-x-autogenerated-id_2"]/div[1]/h2')
        #WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="app"]/div/div/div/div[3]/div[2]/div/div/div[2]/div/div[1]/div')))
        #self.assertIn(info_banner.text, "Chicago")


        



    

if __name__ == "__main__":
    unittest.main()
